function raicar_generateIndex (totalComp, indexNm)
%
% function raicar_generateIndex (totalComp, indexNm)
%
% Author: Zhi Yang
% Version: 2.0
% Last change: July 1, 2007
% 
% Purpose: 
%   generate the index page of the webreport
% Input:
%   totalComp : total number of the components
%   indexNm   : the path and prefix (without html suffix) of the index page
% Output:
%   None
%
compPerPage = 40;
% check input
if ~isa (totalComp, 'numeric') || mod (totalComp, 1) ~= 0
    error ('raicar_generateIndex: the first input, totalComp, is not integer');
end
if exist (strcat (indexNm, '1.html'), 'file')
    error ('raicar_generateIndex: the target file exist!');
end

numPages = ceil (totalComp/compPerPage);

for page = 1:numPages
% generate index page
fid = fopen (strcat (indexNm, num2str(page), '.html'), 'w');
fprintf (fid, '<html>\n');
fprintf (fid, '    <head>\n');
fprintf (fid, '             <title>RAICAR Report: Index (page %d)</title>\n', page);
fprintf (fid, '	   </head>\n');
fprintf (fid, '	   <body>\n');
fprintf (fid, '		<h1 align="center">RAICAR Report (page %d)</h1>\n', page);
if numPages ~= 1
    fprintf (fid, '         <h2 align="center">');
    for p = 1:numPages
        fprintf (fid, '<a href="%s">%d</a>	', strcat ('00index', num2str(p), '.html'), p);
    end
    fprintf (fid, '</h2>\n');
end

fprintf (fid, '         <hr>\n'); 
fprintf (fid, '		<br><br>\n');
fprintf (fid, '		<table border="0" cellpadding="10">\n');

for compInd = 1:min (compPerPage, totalComp-compPerPage*(page-1))
comp = (page-1)*compPerPage+compInd;

fprintf (fid, '		    <tr>\n');
fprintf (fid, '			<th align="center" rowspan="2"><h4>Component %d</h4></th>\n', comp);
fn = sprintf ('map_IC%d.png', comp);
fn2 = sprintf ('IC_%d.html', comp);
fprintf (fid, '			<td align="left" rowspan="2"><a href="%s"><img src="%s" width="500" height="550" border="0"\\></td>\n', fn2, fn);
fn = sprintf ('rank_IC%d.png', comp);
fprintf (fid, '                 <td align="center">Reproducibility Rank<br><a href="%s"><img src="%s" align="center" width="250" height="250" border="0"\\></td>\n', fn2, fn);
fprintf (fid, '             </tr>\n');
fn = sprintf ('tc_IC%d.png', comp);
fprintf (fid, '		    <tr align="left">\n');
fprintf (fid, '                 <td align="center">Time Courses/Power Spectra<br><a href="%s"><img src="%s" align="center" width="400" height="280" border="0"\\></td>\n', fn2, fn);
fprintf (fid, '             </tr>\n');

end

fprintf (fid, '		</table>\n');

if numPages ~= 1
    fprintf (fid, '         </br></br>\n');
    fprintf (fid, '         <h2 align="center">');
    for p = 1:numPages
        fprintf (fid, '<a href="%s">%d</a>	', strcat ('00index', num2str(p), '.html'), p);
    end
    fprintf (fid, '</h2>\n');
end
    
fprintf (fid, '         </br></br>\n');
fprintf (fid, '         <hr>\n');
fprintf (fid, '         <h3 align="center">Automatically Generated by RAICAR 2.0</h3>\n');
fprintf (fid, '         </br></br>\n');
fprintf (fid, '    </body>\n');
fprintf (fid, '</html>\n');
fclose (fid);
end


